apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast-api
  template:
    metadata:
      labels:
        app: forecast-api
    spec:
      containers:
      - name: forecast-api
        image: openaidemoacr.azurecr.io/forecast-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: GENERATE_ENDPOINT
          value: "http://10.0.69.37/generate"
        - name: GENERATE_ENDPOINT_CHAT
          value: "http://10.0.160.68/chat"